# ビルド環境
FROM node:16-alpine as build-stage
WORKDIR /src
COPY ./src .
RUN yarn install
RUN yarn generate

# 本番環境
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /src/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
